docker-exim :
 image: exim:4.89
 container_name: docker-exim
 hostname: exim
 restart: always
 ports:
  - "25:25"
  - "465:465"
 volumes:
  - "/opt/docker-exim/config/exim-smtp.conf:/etc/exim/exim.conf:ro"
  - "/opt/docker-exim/log/:/var/log/exim/"
  - "/opt/docker-exim/ssl/:/etc/ssl/:ro"
